name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - name: testClassCadastre_Constructor 1 punkt
      id: testclasscadastre_constructor-1-punkt
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testClassCadastre_Constructor 1 punkt
        setup-command: ''
        command: gradle test --tests at.ac.fhcampuswien.AppTest.testClassCadastre_Constructor
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTCLASSCADASTRE_CONSTRUCTOR-1-PUNKT_RESULTS: "${{steps.testclasscadastre_constructor-1-punkt.outputs.result}}"
      with:
        runners: testclasscadastre_constructor-1-punkt
